Repository robocin/ssl-core, pull requests merged in 2024-02, with the labels that each got.

#20 Add ISSUE_TEMPLATE files
  .github/ISSUE_TEMPLATE/00-feature-request.yml
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, enhancement

#21 Update .clang-tidy to match the desired style
  .clang-tidy
Labels: enhancement

#66 Enable blank issues
  .github/ISSUE_TEMPLATE/00-feature-request.yaml
  .github/ISSUE_TEMPLATE/01-bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug, documentation

#49 Add `containers` directory and 'Dockerfile: Build and Push Manually' workflow
  .github/workflows/dockerfile-build-and-push.yaml
  .github/workflows/lint-and-formatting-checker.yaml
  README.md
  containers/README.md
  containers/scripts/benchmark.sh
  containers/scripts/buf.sh
  containers/scripts/cmake.sh
  containers/scripts/cppzmq.sh
  containers/scripts/gcc.sh
  containers/scripts/googletest.sh
  containers/scripts/libzmq.sh
  containers/scripts/llvm.sh
  containers/scripts/ninja.sh
  containers/scripts/protobuf.sh
  containers/scripts/protoc.sh
  containers/ssl-core-cpp-base.Dockerfile
  containers/ssl-core-python-base.Dockerfile
Labels: enhancement

#67 Update the base image for `cpp` development
  .cmake/essentials.cmake
  README.md
  common/README.md
  common/cpp/.devcontainer/Dockerfile
  common/cpp/.devcontainer/devcontainer.json
  common/cpp/CMakeLists.txt
  protocols/CMakeLists.txt
Labels: enhancement

#36 Add sockets libraries
  .cmake/essentials.cmake
  common/cpp/robocin/network/CMakeLists.txt
  common/cpp/robocin/network/udp_multicast_socket_receiver.cpp
  common/cpp/robocin/network/udp_multicast_socket_receiver.h
  common/cpp/robocin/network/udp_multicast_socket_receiver_test.cpp
  common/cpp/robocin/network/zmq_publisher_socket.cpp
  common/cpp/robocin/network/zmq_publisher_socket.h
  common/cpp/robocin/network/zmq_publisher_socket_test.cpp
  common/cpp/robocin/network/zmq_subscriber_socket.cpp
  common/cpp/robocin/network/zmq_subscriber_socket.h
  common/cpp/robocin/network/zmq_subscriber_socket_test.cpp
Labels: enhancement
