Repository robocin/ssl-core, pull requests merged in 2024-11, with the labels that each got.

#73 Add RotateOnSelf Motion
  navigation-ms/navigation-luffy/navigation/processing/entities/robot_move.cpp
  navigation-ms/navigation-luffy/navigation/processing/entities/robot_move.h
  navigation-ms/navigation-luffy/navigation/processing/motion_parser/motion_parser.cpp
Labels: enhancement, HIGH PRIORITY

#81 Add referee service subscription
  behavior-ms/behavior-bruxo/behavior/behavior_main.cpp
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/message_receiver.cpp
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/message_receiver.h
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload.cpp
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload.h
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload_mapper.cpp
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.h
Labels: enhancement, HIGH PRIORITY

#79 [behavior-ms] Add behavior state machine
  behavior-ms/behavior-bruxo/behavior/behavior_main.cpp
  behavior-ms/behavior-bruxo/behavior/processing/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/behavior/behavior_message.h
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/goalkeeper/goalkeeper_state_machine.cpp
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/goalkeeper/goalkeeper_state_machine.h
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/goalkeeper/states/guard.cpp
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/goalkeeper/states/guard.h
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/goalkeeper/states/other.cpp
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/goalkeeper/states/other.h
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/istate_machine.cpp
  behavior-ms/behavior-bruxo/behavior/processing/state_machine/istate_machine.h
  docker-compose.dev.yaml
Labels: enhancement, HIGH PRIORITY

#72 Add GoToPoint Motion
  navigation-ms/navigation-luffy/navigation/processing/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/processing/entities/robot_move.cpp
  navigation-ms/navigation-luffy/navigation/processing/motion_parser/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/processing/motion_parser/motion_parser.cpp
  navigation-ms/navigation-luffy/navigation/processing/navigation_processor.cpp
  navigation-ms/navigation-luffy/navigation/processing/utils/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/processing/utils/moving_profile_util.cpp
  navigation-ms/navigation-luffy/navigation/processing/utils/moving_profile_util.h
Labels: enhancement, HIGH PRIORITY

#84 [decision-ms] Fix GameStatus message
  decision-ms/decision-guardiola/decision/parameters/parameters.h
  decision-ms/decision-guardiola/decision/processing/CMakeLists.txt
  decision-ms/decision-guardiola/decision/processing/coach/icoach.h
  decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
  decision-ms/decision-guardiola/decision/processing/decision_processor.h
  decision-ms/decision-guardiola/decision/processing/messages/common/game_command/game_command_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/game_command/game_command_message.h
  decision-ms/decision-guardiola/decision/processing/messages/common/game_event/game_event_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/game_event/game_event_message.h
  decision-ms/decision-guardiola/decision/processing/messages/common/robot_id/robot_id_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/robot_id/robot_id_message.h
  decision-ms/decision-guardiola/decision/processing/messages/referee/game_status_message.cpp
Labels: bug

#86 [decision-ms] Add role manager
  decision-ms/decision-guardiola/decision/processing/coach/role_manager/role_manager.cpp
  decision-ms/decision-guardiola/decision/processing/coach/role_manager/role_manager.h
Labels: enhancement

#85 [behavior-ms] Add gameStatus message class
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.h
  behavior-ms/behavior-bruxo/behavior/processing/entities/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/entities/world.cpp
  behavior-ms/behavior-bruxo/behavior/processing/entities/world.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/game_command/game_command_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/game_command/game_command_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/game_event/game_event_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/game_event/game_event_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/peripheral_actuation/peripheral_actuation.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/peripheral_actuation/peripheral_actuation.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_id/robot_id.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_id/robot_id.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_kick/kick_command.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_kick/kick_command.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/decision/decision_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/decision/decision_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/ball/ball_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/ball/ball_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/detection/detection_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/detection/detection_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/field/field_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/field/field_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/robot/robot_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/robot/robot_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/referee/game_status_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/referee/game_status_message.h
  decision-ms/decision-guardiola/decision/processing/messages/CMakeLists.txt
Labels: enhancement, HIGH PRIORITY

#91 [decision-ms] Implement RoleManager and Add Goalkeeper Role
  .vscode/c_cpp_properties.json
  decision-ms/decision-guardiola/.vscode/c_cpp_properties.json
  decision-ms/decision-guardiola/cmake-build-debug/.cmake/api/v1/query/cache-v2
  decision-ms/decision-guardiola/cmake-build-debug/.cmake/api/v1/query/cmakeFiles-v1
  decision-ms/decision-guardiola/cmake-build-debug/.cmake/api/v1/query/codemodel-v2
  decision-ms/decision-guardiola/cmake-build-debug/.cmake/api/v1/query/toolchains-v1
  decision-ms/decision-guardiola/decision/decision_main.cpp
  decision-ms/decision-guardiola/decision/processing/CMakeLists.txt
  decision-ms/decision-guardiola/decision/processing/coach/coach.cpp
  decision-ms/decision-guardiola/decision/processing/coach/coach.h
  decision-ms/decision-guardiola/decision/processing/coach/role_manager/role_manager.cpp
  decision-ms/decision-guardiola/decision/processing/coach/role_manager/role_manager.h
  decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
  decision-ms/decision-guardiola/decision/processing/decision_processor.h
  decision-ms/decision-guardiola/decision/processing/entities/world.cpp
  decision-ms/decision-guardiola/decision/processing/entities/world.h
  decision-ms/decision-guardiola/decision/processing/messages/behavior/behavior_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/behavior/behavior_message.h
  decision-ms/decision-guardiola/decision/processing/messages/decision/decision_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/decision/decision_message.h
  decision-ms/decision-guardiola/decision/processing/messages/motion/motion_message.h
  decision-ms/decision-guardiola/decision/processing/messages/planning/planning_message.h
  decision-ms/decision-guardiola/decision/processing/role_manager/CMakeLists.txt
  decision-ms/decision-guardiola/decision/processing/role_manager/role_manager.cpp
  decision-ms/decision-guardiola/decision/processing/role_manager/role_manager.h
  decision-ms/decision-guardiola/decision/processing/role_manager/roles/goalkeeper.cpp
  decision-ms/decision-guardiola/decision/processing/role_manager/roles/goalkeeper.h
  decision-ms/decision-guardiola/decision/processing/role_manager/roles/irole.cpp
  decision-ms/decision-guardiola/decision/processing/role_manager/roles/irole.h
  docker-compose.dev.yaml
  protocols/protocols/decision/decision.proto
Labels: enhancement, good first issue, help wanted

#97 Add field in behavior world
  behavior-ms/behavior-bruxo/behavior/parameters/parameters.h
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-bruxo/behavior/processing/entities/world.cpp
  behavior-ms/behavior-bruxo/behavior/processing/entities/world.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/decision/decision_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/perception/field/field_message.h
Labels: enhancement, help wanted, HIGH PRIORITY

#98 Feat behavior analyzers
  behavior-ms/behavior-bruxo/behavior/processing/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/analyzer/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/analyzer/ball_analyzer.cpp
  behavior-ms/behavior-bruxo/behavior/processing/analyzer/ball_analyzer.h
  behavior-ms/behavior-bruxo/behavior/processing/analyzer/field_analyzer.cpp
  behavior-ms/behavior-bruxo/behavior/processing/analyzer/field_analyzer.h
Labels: enhancement

#100 [common] Add Line class to `geometry`
  common/cpp/robocin/geometry/CMakeLists.txt
  common/cpp/robocin/geometry/line.cpp
  common/cpp/robocin/geometry/line.h
Labels: enhancement

#109 Add peripheral actuation to motion
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/peripheral_actuation/peripheral_actuation.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/peripheral_actuation/peripheral_actuation.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_kick/kick_command.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_kick/kick_command.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/motion/motion_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/motion/motion_message.h
Labels: enhancement

#114 [behavior-ms] Add CBR compose
  docker-compose.cbr.yaml
Labels: enhancement
