Repository robocin/ssl-core, pull requests merged in 2024-10, with the labels that each got.

#3 Adds communication protocol
  protocols/README.md
  protocols/protocols/common/message_type.proto
  protocols/protocols/communication/README.md
  protocols/protocols/communication/robot_info.proto
Labels: enhancement, good first issue

#10 Add navigation devcontainer
  docker-compose.dev.yaml
  navigation-ms/README.md
  navigation-ms/navigation-luffy/.devcontainer/devcontainer.json
  navigation-ms/navigation-luffy/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation-luffy.Dockerfile
  navigation-ms/navigation-luffy/navigation-luffy.code-workspace
  navigation-ms/navigation-luffy/navigation/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/navigation_main.cpp
Labels: enhancement, good first issue

#17 Add peripheral actuation to navigation proto
  protocols/protocols/navigation/navigation.proto
Labels: bug

#19 Use common robot id
  protocols/protocols/navigation/navigation.proto
Labels: enhancement

#20 Enable game controller view from .dev compose
  docker-compose.dev.yaml
Labels: bug

#24 Add controller classes to communication
  communication-ms/communication-jaiminho/communication/controller/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/controller/consumer_controller.cpp
  communication-ms/communication-jaiminho/communication/controller/consumer_controller.h
  communication-ms/communication-jaiminho/communication/controller/icontroller.cpp
  communication-ms/communication-jaiminho/communication/controller/icontroller.h
  communication-ms/communication-jaiminho/communication/controller/producer_controller.cpp
  communication-ms/communication-jaiminho/communication/controller/producer_controller.h
Labels: enhancement, good first issue, help wanted

#26 Add processing classes to communication
  communication-ms/communication-jaiminho/communication/processing/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/processing/communication_processor.cpp
  communication-ms/communication-jaiminho/communication/processing/communication_processor.h
  communication-ms/communication-jaiminho/communication/processing/robot_command/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/processing/robot_command/robot_command_mapper.cpp
  communication-ms/communication-jaiminho/communication/processing/robot_command/robot_command_mapper.h
Labels: enhancement, good first issue, help wanted

#27 Add parameters class to communication
  communication-ms/communication-jaiminho/communication/parameters/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/parameters/parameters.cpp
  communication-ms/communication-jaiminho/communication/parameters/parameters.h
Labels: enhancement, good first issue, help wanted

#16 Add decision devcontainer
  decision-ms/README.md
  decision-ms/decision-guardiola/.devcontainer/devcontainer.json
  decision-ms/decision-guardiola/CMakeLists.txt
  decision-ms/decision-guardiola/decision-guardiola.Dockerfile
  decision-ms/decision-guardiola/decision-guardiola.code-workspace
  decision-ms/decision-guardiola/decision/CMakeLists.txt
  decision-ms/decision-guardiola/decision/decision_main.cpp
  docker-compose.dev.yaml
Labels: enhancement, good first issue

#21 Add decision service pub/sub infra
  common/cpp/robocin/wip/service_discovery/addresses.h
  decision-ms/decision-guardiola/decision/CMakeLists.txt
  decision-ms/decision-guardiola/decision/controller/CMakeLists.txt
  decision-ms/decision-guardiola/decision/controller/consumer_controller.cpp
  decision-ms/decision-guardiola/decision/controller/consumer_controller.h
  decision-ms/decision-guardiola/decision/controller/icontroller.cpp
  decision-ms/decision-guardiola/decision/controller/icontroller.h
  decision-ms/decision-guardiola/decision/controller/producer_controller.cpp
  decision-ms/decision-guardiola/decision/controller/producer_controller.h
  decision-ms/decision-guardiola/decision/decision_main.cpp
  decision-ms/decision-guardiola/decision/messaging/receiver/CMakeLists.txt
  decision-ms/decision-guardiola/decision/messaging/receiver/message_receiver.cpp
  decision-ms/decision-guardiola/decision/messaging/receiver/message_receiver.h
  decision-ms/decision-guardiola/decision/messaging/receiver/payload.cpp
  decision-ms/decision-guardiola/decision/messaging/receiver/payload.h
  decision-ms/decision-guardiola/decision/messaging/receiver/payload_mapper.cpp
  decision-ms/decision-guardiola/decision/messaging/receiver/payload_mapper.h
  decision-ms/decision-guardiola/decision/messaging/sender/CMakeLists.txt
  decision-ms/decision-guardiola/decision/messaging/sender/message_sender.cpp
  decision-ms/decision-guardiola/decision/messaging/sender/message_sender.h
  decision-ms/decision-guardiola/decision/parameters/CMakeLists.txt
  decision-ms/decision-guardiola/decision/parameters/parameters.cpp
  decision-ms/decision-guardiola/decision/parameters/parameters.h
  decision-ms/decision-guardiola/decision/processing/CMakeLists.txt
  decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
  decision-ms/decision-guardiola/decision/processing/decision_processor.h
  docker-compose.dev.yaml
  protocols/protocols/decision/decision.proto
Labels: bug, enhancement, good first issue, help wanted

#39 Add behavior-zidane devcontainer
  behavior-ms/README.md
  behavior-ms/behavior-zidane/.devcontainer/devcontainer.json
  behavior-ms/behavior-zidane/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior-zidane.Dockerfile
  behavior-ms/behavior-zidane/behavior-zidane.code-workspace
  behavior-ms/behavior-zidane/behavior/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior/behavior_main.cpp
  docker-compose.dev.yaml
Labels: enhancement

#38 Add Geometry.Point2D methods
  common/cpp/robocin/geometry/point2d.h
Labels: enhancement

#40 Add behavior service pub/sub infra
  .vscode/settings.json
  behavior-ms/behavior-zidane/README.md
  behavior-ms/behavior-zidane/behavior-zidane.Dockerfile
  behavior-ms/behavior-zidane/behavior/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior/behavior_main.cpp
  behavior-ms/behavior-zidane/behavior/controller/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior/controller/consumer_controller.cpp
  behavior-ms/behavior-zidane/behavior/controller/consumer_controller.h
  behavior-ms/behavior-zidane/behavior/controller/icontroller.cpp
  behavior-ms/behavior-zidane/behavior/controller/icontroller.h
  behavior-ms/behavior-zidane/behavior/controller/producer_controller.cpp
  behavior-ms/behavior-zidane/behavior/controller/producer_controller.h
  behavior-ms/behavior-zidane/behavior/messaging/receiver/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior/messaging/receiver/message_receiver.cpp
  behavior-ms/behavior-zidane/behavior/messaging/receiver/message_receiver.h
  behavior-ms/behavior-zidane/behavior/messaging/receiver/payload.cpp
  behavior-ms/behavior-zidane/behavior/messaging/receiver/payload.h
  behavior-ms/behavior-zidane/behavior/messaging/receiver/payload_mapper.cpp
  behavior-ms/behavior-zidane/behavior/messaging/receiver/payload_mapper.h
  behavior-ms/behavior-zidane/behavior/messaging/sender/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior/messaging/sender/message_sender.cpp
  behavior-ms/behavior-zidane/behavior/messaging/sender/message_sender.h
  behavior-ms/behavior-zidane/behavior/parameters/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior/parameters/parameters.cpp
  behavior-ms/behavior-zidane/behavior/parameters/parameters.h
  behavior-ms/behavior-zidane/behavior/processing/CMakeLists.txt
  behavior-ms/behavior-zidane/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-zidane/behavior/processing/behavior_processor.h
  common/cpp/robocin/wip/service_discovery/addresses.h
  decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
  protocols/protocols/behavior/behavior.proto
Labels: enhancement, good first issue

#44 Refactor protocols
  protocols/protocols/behavior/behavior_unification.proto
  protocols/protocols/behavior/motion.proto
  protocols/protocols/behavior/planning.proto
  protocols/protocols/navigation/navigation.proto
  protocols/protocols/navigation/planning.proto
Labels: bug, help wanted

#45 refactor decison processor
  decision-ms/decision-guardiola/decision/messaging/receiver/payload.cpp
  decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
  decision-ms/decision-guardiola/decision/processing/decision_processor.h
Labels: enhancement

#46 synchronize behavior pub/sub processor
  behavior-ms/behavior-zidane/behavior/messaging/receiver/message_receiver.cpp
  behavior-ms/behavior-zidane/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-zidane/behavior/processing/behavior_processor.h
Labels: enhancement

#47 Add navigation service
  common/cpp/robocin/wip/service_discovery/addresses.h
  navigation-ms/navigation-luffy/navigation/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/controller/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/controller/consumer_controller.cpp
  navigation-ms/navigation-luffy/navigation/controller/consumer_controller.h
  navigation-ms/navigation-luffy/navigation/controller/icontroller.cpp
  navigation-ms/navigation-luffy/navigation/controller/icontroller.h
  navigation-ms/navigation-luffy/navigation/controller/producer_controller.cpp
  navigation-ms/navigation-luffy/navigation/controller/producer_controller.h
  navigation-ms/navigation-luffy/navigation/messaging/receiver/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/messaging/receiver/message_receiver.cpp
  navigation-ms/navigation-luffy/navigation/messaging/receiver/message_receiver.h
  navigation-ms/navigation-luffy/navigation/messaging/receiver/payload.cpp
  navigation-ms/navigation-luffy/navigation/messaging/receiver/payload.h
  navigation-ms/navigation-luffy/navigation/messaging/receiver/payload_mapper.cpp
  navigation-ms/navigation-luffy/navigation/messaging/receiver/payload_mapper.h
  navigation-ms/navigation-luffy/navigation/messaging/sender/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/messaging/sender/message_sender.cpp
  navigation-ms/navigation-luffy/navigation/messaging/sender/message_sender.h
  navigation-ms/navigation-luffy/navigation/navigation_main.cpp
  navigation-ms/navigation-luffy/navigation/parameters/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/parameters/parameters.cpp
  navigation-ms/navigation-luffy/navigation/parameters/parameters.h
  navigation-ms/navigation-luffy/navigation/processing/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/processing/motion_parser/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/processing/motion_parser/motion_parser.cpp
  navigation-ms/navigation-luffy/navigation/processing/motion_parser/motion_parser.h
  navigation-ms/navigation-luffy/navigation/processing/navigation_processor.cpp
  navigation-ms/navigation-luffy/navigation/processing/navigation_processor.h
  navigation-ms/navigation-luffy/navigation/processing/utils/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/processing/utils/robot_move.cpp
  navigation-ms/navigation-luffy/navigation/processing/utils/robot_move.h
Labels: enhancement

#49 Add communication service
  common/cpp/robocin/network/CMakeLists.txt
  common/cpp/robocin/network/udp_multicast_socket_sender.cpp
  common/cpp/robocin/network/udp_multicast_socket_sender.h
  common/cpp/robocin/wip/service_discovery/addresses.h
  communication-ms/README.md
  communication-ms/communication-jaiminho/.devcontainer/devcontainer.json
  communication-ms/communication-jaiminho/CMakeLists.txt
  communication-ms/communication-jaiminho/communication-jaiminho.Dockerfile
  communication-ms/communication-jaiminho/communication-jaiminho.code-workspace
  communication-ms/communication-jaiminho/communication/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/communication_main.cpp
  communication-ms/communication-jaiminho/communication/controller/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/controller/consumer_controller.cpp
  communication-ms/communication-jaiminho/communication/controller/consumer_controller.h
  communication-ms/communication-jaiminho/communication/controller/icontroller.cpp
  communication-ms/communication-jaiminho/communication/controller/icontroller.h
  communication-ms/communication-jaiminho/communication/controller/producer_controller.cpp
  communication-ms/communication-jaiminho/communication/controller/producer_controller.h
  communication-ms/communication-jaiminho/communication/messaging/receiver/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/messaging/receiver/message_receiver.cpp
  communication-ms/communication-jaiminho/communication/messaging/receiver/message_receiver.h
  communication-ms/communication-jaiminho/communication/messaging/receiver/payload.cpp
  communication-ms/communication-jaiminho/communication/messaging/receiver/payload.h
  communication-ms/communication-jaiminho/communication/messaging/receiver/payload_mapper.cpp
  communication-ms/communication-jaiminho/communication/messaging/receiver/payload_mapper.h
  communication-ms/communication-jaiminho/communication/messaging/sender/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/messaging/sender/message_sender.cpp
  communication-ms/communication-jaiminho/communication/messaging/sender/message_sender.h
  communication-ms/communication-jaiminho/communication/parameters/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/parameters/parameters.cpp
  communication-ms/communication-jaiminho/communication/parameters/parameters.h
  communication-ms/communication-jaiminho/communication/processing/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/processing/communication_processor.cpp
  communication-ms/communication-jaiminho/communication/processing/communication_processor.h
  communication-ms/communication-jaiminho/communication/processing/robot_command/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/processing/robot_command/robot_command_mapper.cpp
  communication-ms/communication-jaiminho/communication/processing/robot_command/robot_command_mapper.h
  docker-compose.dev.yaml
Labels: enhancement, good first issue

#52 Add new microservices .lab compose
  docker-compose.lab.yaml
Labels: enhancement

#54 Add proto convertible interface
  common/cpp/robocin/utility/CMakeLists.txt
  common/cpp/robocin/utility/iproto_convertible.cpp
  common/cpp/robocin/utility/iproto_convertible.h
Labels: enhancement

#53 Refactor behavior name
  behavior-ms/behavior-zidane/.devcontainer/devcontainer.json
  behavior-ms/behavior-zidane/README.md
  behavior-ms/behavior-zidane/behavior-bruxo.Dockerfile
  behavior-ms/behavior-zidane/behavior-bruxo.code-workspace
  behavior-ms/behavior-zidane/behavior/behavior_main.cpp
  docker-compose.dev.yaml
  docker-compose.lab.yaml
Labels: bug

#50 Fix remove ilogs
  communication-ms/communication-jaiminho/communication/messaging/receiver/payload_mapper.cpp
  navigation-ms/navigation-luffy/navigation/messaging/receiver/payload_mapper.cpp
Labels: enhancement

#57 Fix .lab compose
  docker-compose.lab.yaml
Labels: bug

#58 Fix behavior-ms
  behavior-ms/behavior-bruxo/.devcontainer/devcontainer.json
  behavior-ms/behavior-bruxo/CMakeLists.txt
  behavior-ms/behavior-bruxo/README.md
  behavior-ms/behavior-bruxo/behavior-bruxo.Dockerfile
  behavior-ms/behavior-bruxo/behavior-bruxo.code-workspace
  behavior-ms/behavior-bruxo/behavior/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/behavior_main.cpp
  behavior-ms/behavior-bruxo/behavior/controller/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/controller/consumer_controller.cpp
  behavior-ms/behavior-bruxo/behavior/controller/consumer_controller.h
  behavior-ms/behavior-bruxo/behavior/controller/icontroller.cpp
  behavior-ms/behavior-bruxo/behavior/controller/icontroller.h
  behavior-ms/behavior-bruxo/behavior/controller/producer_controller.cpp
  behavior-ms/behavior-bruxo/behavior/controller/producer_controller.h
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/message_receiver.cpp
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/message_receiver.h
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload.cpp
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload.h
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload_mapper.cpp
  behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload_mapper.h
  behavior-ms/behavior-bruxo/behavior/messaging/sender/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/messaging/sender/message_sender.cpp
  behavior-ms/behavior-bruxo/behavior/messaging/sender/message_sender.h
  behavior-ms/behavior-bruxo/behavior/parameters/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/parameters/parameters.cpp
  behavior-ms/behavior-bruxo/behavior/parameters/parameters.h
  behavior-ms/behavior-bruxo/behavior/processing/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.h
Labels: bug

#77 Fix common formatting
  common/cpp/robocin/geometry/mathematics.cpp
Labels: bug, enhancement

#75 [common] Add const reference to proto interface methods
  common/cpp/robocin/utility/iproto_convertible.h
Labels: enhancement, debt, HIGH PRIORITY

#60 [decision-ms] Add message mappers
  common/cpp/robocin/utility/iproto_convertible.h
  decision-ms/decision-guardiola/decision/processing/CMakeLists.txt
  decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
  decision-ms/decision-guardiola/decision/processing/messages/CMakeLists.txt
  decision-ms/decision-guardiola/decision/processing/messages/behavior/behavior_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/behavior/behavior_message.h
  decision-ms/decision-guardiola/decision/processing/messages/common/game_command/game_command_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/game_command/game_command_message.h
  decision-ms/decision-guardiola/decision/processing/messages/common/game_event/game_event_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/game_event/game_event_message.h
  decision-ms/decision-guardiola/decision/processing/messages/common/peripheral_actuation/peripheral_actuation.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/peripheral_actuation/peripheral_actuation.h
  decision-ms/decision-guardiola/decision/processing/messages/common/robot_id/robot_id_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/robot_id/robot_id_message.h
  decision-ms/decision-guardiola/decision/processing/messages/common/robot_kick/kick_command.cpp
  decision-ms/decision-guardiola/decision/processing/messages/common/robot_kick/kick_command.h
  decision-ms/decision-guardiola/decision/processing/messages/decision/decision_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/decision/decision_message.h
  decision-ms/decision-guardiola/decision/processing/messages/motion/motion_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/motion/motion_message.h
  decision-ms/decision-guardiola/decision/processing/messages/perception/ball/ball_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/perception/ball/ball_message.h
  decision-ms/decision-guardiola/decision/processing/messages/perception/detection/detection_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/perception/detection/detection_message.h
  decision-ms/decision-guardiola/decision/processing/messages/perception/field/field_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/perception/field/field_message.h
  decision-ms/decision-guardiola/decision/processing/messages/perception/robot/robot_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/perception/robot/robot_message.h
  decision-ms/decision-guardiola/decision/processing/messages/planning/planning_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/planning/planning_message.h
  decision-ms/decision-guardiola/decision/processing/messages/referee/game_status_message.cpp
  decision-ms/decision-guardiola/decision/processing/messages/referee/game_status_message.h
  docker-compose.dev.yaml
Labels: enhancement, help wanted, HIGH PRIORITY

#76 [decision-ms] Add decision world
  decision-ms/decision-guardiola/decision/processing/entities/CMakeLists.txt
  decision-ms/decision-guardiola/decision/processing/entities/world.cpp
  decision-ms/decision-guardiola/decision/processing/entities/world.h
Labels: enhancement, good first issue

#66 Fix file formatting
  common/cpp/robocin/utility/iproto_convertible.h
  communication-ms/communication-jaiminho/communication/processing/robot_command/robot_command_mapper.cpp
  decision-ms/decision-guardiola/.devcontainer/devcontainer.json
  decision-ms/decision-guardiola/decision-guardiola.code-workspace
  decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
  navigation-ms/navigation-luffy/navigation-luffy.code-workspace
  navigation-ms/navigation-luffy/navigation/messaging/receiver/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/parameters/CMakeLists.txt
  navigation-ms/navigation-luffy/navigation/processing/motion_parser/CMakeLists.txt
  protocols/protocols/behavior/behavior.proto
  protocols/protocols/behavior/behavior_unification.proto
  protocols/protocols/behavior/motion.proto
  protocols/protocols/behavior/planning.proto
  protocols/protocols/common/feedback.proto
  protocols/protocols/common/message_type.proto
  protocols/protocols/common/peripheral_actuation.proto
  protocols/protocols/common/robot_dribbler.proto
  protocols/protocols/common/robot_kick.proto
  protocols/protocols/common/robot_motor.proto
  protocols/protocols/common/robot_pose.proto
  protocols/protocols/common/robot_velocity.proto
  protocols/protocols/communication/README.md
  protocols/protocols/communication/robot_info.proto
  protocols/protocols/decision/decision.proto
  protocols/protocols/navigation/navigation.proto
  protocols/protocols/playback/README.md
Labels: bug, help wanted

#62 Add behavior message mappers
  behavior-ms/behavior-bruxo/behavior/processing/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
  behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/CMakeLists.txt
  behavior-ms/behavior-bruxo/behavior/processing/messages/behavior/behavior_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/behavior/behavior_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_id/robot_id.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_id/robot_id.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/motion/motion_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/motion/motion_message.h
  behavior-ms/behavior-bruxo/behavior/processing/messages/planning/planning_message.cpp
  behavior-ms/behavior-bruxo/behavior/processing/messages/planning/planning_message.h
Labels: enhancement, good first issue, help wanted

#67 Add communication message mappers
  communication-ms/communication-jaiminho/communication/communication_main.cpp
  communication-ms/communication-jaiminho/communication/controller/consumer_controller.cpp
  communication-ms/communication-jaiminho/communication/processing/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/processing/communication_processor.cpp
  communication-ms/communication-jaiminho/communication/processing/communication_processor.h
  communication-ms/communication-jaiminho/communication/processing/messages/CMakeLists.txt
  communication-ms/communication-jaiminho/communication/processing/messages/common/message_type/message_type.cpp
  communication-ms/communication-jaiminho/communication/processing/messages/common/message_type/message_type.h
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_dribbler/robot_dribbler.cpp
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_dribbler/robot_dribbler.h
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_id/robot_id.cpp
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_id/robot_id.h
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_kick/robot_kick.cpp
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_kick/robot_kick.h
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_velocity/robot_velocity.cpp
  communication-ms/communication-jaiminho/communication/processing/messages/common/robot_velocity/robot_velocity.h
  communication-ms/communication-jaiminho/communication/processing/messages/communication/communication_message.cpp
  communication-ms/communication-jaiminho/communication/processing/messages/communication/communication_message.h
  communication-ms/communication-jaiminho/communication/processing/messages/flags/flags.cpp
  communication-ms/communication-jaiminho/communication/processing/messages/flags/flags.h
  communication-ms/communication-jaiminho/communication/processing/robot_command/CMakeLists.txt
  protocols/protocols/common/robot_kick.proto
  protocols/protocols/communication/robot_info.proto
Labels: enhancement, help wanted
