Repository robocin/ssl-core, pull requests merged in 2024-03, with the labels that each got.

#53 Add gateway initial experiment
  experiments/README.md
  experiments/gateway/proxy-multiclient-single-service/.devcontainer/Dockerfile
  experiments/gateway/proxy-multiclient-single-service/.devcontainer/devcontainer.json
  experiments/gateway/proxy-multiclient-single-service/CMakeLists.txt
  experiments/gateway/proxy-multiclient-single-service/README.md
  experiments/gateway/proxy-multiclient-single-service/gateway/CMakeLists.txt
  experiments/gateway/proxy-multiclient-single-service/gateway/client_main.cpp
  experiments/gateway/proxy-multiclient-single-service/gateway/gateway_main.cpp
  experiments/gateway/proxy-multiclient-single-service/gateway/service_main.cpp
Labels: experiment

#62 Add fuzzy_compare library
  common/cpp/robocin/utility/CMakeLists.txt
  common/cpp/robocin/utility/README.md
  common/cpp/robocin/utility/concepts.h
  common/cpp/robocin/utility/concepts_test.cpp
  common/cpp/robocin/utility/epsilon.h.in
  common/cpp/robocin/utility/fuzzy_compare.cpp
  common/cpp/robocin/utility/fuzzy_compare.h
  common/cpp/robocin/utility/fuzzy_compare_test.cpp
  common/cpp/robocin/utility/internal/test/epsilon_injector.h
  common/cpp/robocin/utility/type_traits.cpp
  common/cpp/robocin/utility/type_traits.h
  common/cpp/robocin/utility/type_traits_test.cpp
Labels: enhancement

#82 Refactor `gateway`
  .cmake/essentials.cmake
  gateway/gateway-augusto/.devcontainer/Dockerfile
  gateway/gateway-augusto/gateway/CMakeLists.txt
  gateway/gateway-augusto/gateway/controller/CMakeLists.txt
  gateway/gateway-augusto/gateway/controller/asynchronous_sockets_controller.cpp
  gateway/gateway-augusto/gateway/controller/asynchronous_sockets_controller.h
  gateway/gateway-augusto/gateway/controller/icontroller.cpp
  gateway/gateway-augusto/gateway/controller/icontroller.h
  gateway/gateway-augusto/gateway/controller/synchronous_sockets_controller.cpp
  gateway/gateway-augusto/gateway/controller/synchronous_sockets_controller.h
  gateway/gateway-augusto/gateway/controller/third_party_sockets_controller.cpp
  gateway/gateway-augusto/gateway/controller/third_party_sockets_controller.h
  gateway/gateway-augusto/gateway/controllers/controller.cpp
  gateway/gateway-augusto/gateway/gateway_main.cpp
  gateway/gateway-augusto/gateway/nlohmann/json.hpp
  gateway/gateway-augusto/gateway/service_discovery.h
Labels: enhancement

#84 Update README.md
  README.md
Labels: bug, documentation

#85 Refactor `thread_pool`
  common/cpp/robocin/concurrency/thread_pool.cpp
  common/cpp/robocin/concurrency/thread_pool.h
  common/cpp/robocin/concurrency/thread_pool_test.cpp
  experiments/thread_pool/.devcontainer/Dockerfile
  experiments/thread_pool/.devcontainer/devcontainer.json
  experiments/thread_pool/CMakeLists.txt
Labels: enhancement

#61 Add ThreadPool library and quick experiment
  common/cpp/robocin/concurrency/CMakeLists.txt
  common/cpp/robocin/concurrency/README.md
  common/cpp/robocin/concurrency/thread_pool.cpp
  common/cpp/robocin/concurrency/thread_pool.h
  common/cpp/robocin/concurrency/thread_pool_test.cpp
  experiments/thread_pool/.devcontainer/Dockerfile
  experiments/thread_pool/.devcontainer/devcontainer.json
  experiments/thread_pool/CMakeLists.txt
  experiments/thread_pool/README.md
  experiments/thread_pool/impl/CMakeLists.txt
  experiments/thread_pool/impl/thread_pool_main.cpp
Labels: enhancement, experiment
